Hw avl
illided/SPbU-Homework pull request #10
Opened 2020-05-18 17:43 UTC by illided

2020-05-20 18:48 UTC, SpirinEgor requested changes
Вижу тесты над AVL, но не вижу тесты над Node

2020-05-20 18:48 UTC, SpirinEgor commented on src/main/kotlin/spbuhomework/hwAVL/AVL.kt
> +open class AVL<K : Comparable<K>, V> : Map<K, V> {
Для чего `open`

2020-05-20 18:48 UTC, SpirinEgor commented on src/main/kotlin/spbuhomework/hwAVL/AVL.kt
> +            }
Проверку на null и последнее условие можно убрать, они автоматически выполняются на следующей итерации. А вот код станет чуть чище

2020-05-20 18:48 UTC, SpirinEgor commented on src/main/kotlin/spbuhomework/hwAVL/AVL.kt
> +        return false
У коллекций есть специальный метод для этого

2020-05-30 15:30 UTC, SpirinEgor requested changes

2020-05-30 15:30 UTC, SpirinEgor commented on src/main/kotlin/spbuhomework/hwAVL/AVL.kt
> +        walk.toSpecificNode(key, { it.key == key }) ?: return false
`return walk.toSpecific... `

2020-05-30 15:30 UTC, SpirinEgor commented on src/main/kotlin/spbuhomework/hwAVL/AVL.kt
> +        return values.contains(value)
Такие функции удобнее писать через `=`
```
override fun x() : Boolean = values.contains(value)
```

2020-05-30 15:30 UTC, SpirinEgor commented on src/main/kotlin/spbuhomework/hwAVL/AVL.kt
> +    }
Аналогично можно в 1 линию написать

2020-05-30 15:30 UTC, SpirinEgor commented on src/main/kotlin/spbuhomework/hwAVL/AVL.kt
> +            val currentRoot = root ?: return
А если root будет null, то что произойдёт?

2020-05-30 15:30 UTC, SpirinEgor commented on src/test/kotlin/spbuhomework/hwAVL/NodeTest.kt
> +        assertTrue(myEntry.key == 5 && myEntry.value == "Hello")
Разнеси это в 2 assert.
Если он упадёт, то непонятно из-за какой части выражения

2020-05-30 15:37 UTC, illided commented on src/main/kotlin/spbuhomework/hwAVL/AVL.kt
> +            val currentRoot = root ?: return
А как root может быть null если там есть хоть какой то Node?
Здесь эта проверка стоит потому котлину не обьяснишь это, буду рад если скажете как это лучше сделать.

2020-06-05 15:33 UTC, SpirinEgor commented on src/main/kotlin/spbuhomework/hwAVL/AVL.kt
> +            val currentRoot = root ?: return
Могу предложить в `everywhereAndDo` принимать `Node?`
Затем в самом начале проверять, если null, то сразу делать `return`.
Мне кажется, что это много где улучшит код, ибо все проверки перенесутя в одно место

2020-06-06 10:17 UTC, SpirinEgor approved these changes

2020-06-07 09:13 UTC, merged