Sem2 task5.1
illided/SPbU-Homework pull request #13
Opened 2020-05-25 10:28 UTC by illided

2020-06-06 14:25 UTC, SpirinEgor requested changes
Тестовые файлы должны быть в ресурсах, а не рядом с исходниками

2020-06-06 14:25 UTC, SpirinEgor commented on src/main/kotlin/spbuhomework/hw5/task1/Node.kt
> +    internal class Edge(val letter: Char, var neighbour: Node)
Что за сосед? Тип вершина в конце ребра? А почему она не `val`, как она может поменяться?

2020-06-06 14:25 UTC, SpirinEgor commented on src/main/kotlin/spbuhomework/hw5/task1/Node.kt
> +    internal class Edge(val letter: Char, var neighbour: Node)
Вообще для этого лучше использовать датакласс, он нужен только для хранения, без какой-либо функциональности

2020-06-06 14:25 UTC, SpirinEgor commented on src/main/kotlin/spbuhomework/hw5/task1/Node.kt
> +        return connectedEdges.find { it.letter == char }
Можно сделать map из char в Node, тогда будет и поиск быстрее, без дополнительных функций, а также всякие доп классы будут не нужны

2020-06-06 14:25 UTC, SpirinEgor commented on src/main/kotlin/spbuhomework/hw5/task1/Node.kt
> +            findEdge(input[0])?.neighbour?.removeAndCheckIfUseless(input.drop(1)) == true -> {
Это что? Сравнение с `true`?

2020-06-06 14:25 UTC, SpirinEgor commented on src/main/kotlin/spbuhomework/hw5/task1/Serializable.kt
> +interface Serializable {
https://docs.oracle.com/javase/7/docs/api/java/io/Serializable.html

2020-06-06 14:25 UTC, SpirinEgor commented on src/main/kotlin/spbuhomework/hw5/task1/Trie.kt
> +    private var root = Node()
`val`

2020-06-06 14:25 UTC, SpirinEgor commented on src/main/kotlin/spbuhomework/hw5/task1/Trie.kt
> +        }
Странные функции, лучше чуть увеличить код, но написать аккуратней.

2020-06-06 14:25 UTC, SpirinEgor commented on src/main/kotlin/spbuhomework/hw5/task1/Trie.kt
> +        return if (!root.isContains(input)) {
Аналогично

2020-06-06 14:25 UTC, SpirinEgor commented on src/test/kotlin/spbuhomework/hw5/task1/NodeTest.kt
> +    fun appendNode_wordInput_correctWork() {
Это не юнит тест, такого тут не должно быть

2020-06-06 15:32 UTC, illided commented on src/main/kotlin/spbuhomework/hw5/task1/Node.kt
> +            findEdge(input[0])?.neighbour?.removeAndCheckIfUseless(input.drop(1)) == true -> {
Сравнение с true потому что значение может быть null

2020-06-06 15:58 UTC, illided commented on src/test/kotlin/spbuhomework/hw5/task1/NodeTest.kt
> +    fun appendNode_wordInput_correctWork() {
А что именно исправить?
Удалить все тесты для Node или как то по другому сделать

2020-06-08 08:52 UTC, SpirinEgor commented on src/test/kotlin/spbuhomework/hw5/task1/NodeTest.kt
> +    fun appendNode_wordInput_correctWork() {
Именно этот убрать. Unit тесты проверяют, что функция делает что-то ожидаемое, то есть нужен assert

2020-06-08 09:58 UTC, SpirinEgor requested changes

2020-06-08 09:58 UTC, SpirinEgor commented on src/main/kotlin/spbuhomework/hw5/task1/Serializable.kt
> +interface Serializable {
А зачем ты переписал заново этот интерфейс, он тут не нужен. Надо готовый использовать

2020-06-08 09:58 UTC, SpirinEgor commented on src/main/kotlin/spbuhomework/hw5/task1/Trie.kt
> +        }
Функции не поправил, не надо возвращать `true` или `false` исходя из условия `if`

2020-06-08 09:58 UTC, SpirinEgor commented on src/main/kotlin/spbuhomework/hw5/task1/Trie.kt
> +        return if (!root.isContains(input)) {
Тут тоже не поправил

2020-06-08 10:11 UTC, SpirinEgor approved these changes

2020-09-06 14:11 UTC, merged